//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.14 at 04:48:01 PM IST 
//


package org.wingsource.plugin.lang.xml.wingsite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}api"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}dependency-pom"/>
 *       &lt;/sequence>
 *       &lt;attribute name="jarUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "api",
    "description",
    "dependencyPom"
})
@XmlRootElement(name = "symbol")
public class Symbol {

    protected Api api;
    protected String description;
    @XmlElement(name = "dependency-pom")
    protected String dependencyPom;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String jarUrl;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the api property.
     * 
     * @return
     *     possible object is
     *     {@link Api }
     *     
     */
    public Api getApi() {
        return api;
    }

    /**
     * Sets the value of the api property.
     * 
     * @param value
     *     allowed object is
     *     {@link Api }
     *     
     */
    public void setApi(Api value) {
        this.api = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the dependencyPom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependencyPom() {
        return dependencyPom;
    }

    /**
     * Sets the value of the dependencyPom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependencyPom(String value) {
        this.dependencyPom = value;
    }

    /**
     * Gets the value of the jarUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJarUrl() {
        return jarUrl;
    }

    /**
     * Sets the value of the jarUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJarUrl(String value) {
        this.jarUrl = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
